import type { Metadata } from "next";
import { Barlow_Condensed } from "next/font/google";
import "./globals.css";

const inter = Barlow_Condensed({ subsets: ["latin"],
weight: ["100", "200", "300", "400", "500", "600", "700"],

 });

export const metadata: Metadata = {
  title: "Genre Playlist App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
